# Save this file as _local_config.yml and enter key values

google_api_key: "APIKEY"
search_cx: "SEARCHCX"
openai_api_key: "APIKEY"
gts_account_id: "ACCOUNTID"
gts_api_token: "APITOKEN"
remote_user: "alex"
remote_server: "157.180.28.67"
remote_dir: "/srv/invisibleparade/"