# Save this file as _local_config.yml and enter key values

google_api_key: "APIKEY"
search_cx: "SEARCHCX"
openai_api_key: "APIKEY"
gts_account_id: "ACCOUNTID"
gts_api_token: "APITOKEN"
remote_user: "REMOTE_USER"
remote_server: "REMOTE_SERVER"
remote_dir: "REMOTE_DIR"