#!/usr/bin/env bash

if [ -z "$1" ]; then
  filename="$(ls _drafts | sort -n | head -1)"
  if [ -z "$filename" ]; then
    echo "No drafts found"
    exit -1
  fi
else
  filename="$@.md"
fi

d=$(date +"%Y-%m-%d")
draft="./_drafts/$filename"
post="./_posts/$d-$filename"

mv $draft $post
echo "Published $filename"